plugins:
  - serverless-offline

service: stupid-serverless

provider:
  name: aws
  runtime: nodejs10.x

  stage: dev
  region: us-east-2

  apiKeys:
    - firstApiKey

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:us-east-2:265936875572:table/stupid-words'

functions:
  getRandomText:
    handler: index.handler
    events:
      - http:
          path: /random-text
          method: get
          private: true
          cors: true
  synonymize:
    handler: index.handler
    events:
      - http:
          path: /synonymize
          method: post
          private: true
          cors: true
